USE ROLE AI_ENGINEER;
CREATE SCHEMA IF NOT EXISTS AI_DEVELOPMENT.SI_ENERGY_COMPANY;
USE SCHEMA AI_DEVELOPMENT.SI_ENERGY_COMPANY;

CREATE STAGE CONTRACTS 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' ) 
	COMMENT = 'Stage with customer contracts';

-- Copy parquet files into stage
COPY FILES
  INTO @CONTRACTS
  FROM @AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Energy_Company/docs/;
ALTER STAGE CONTRACTS REFRESH;

-- Create Notebooks
CREATE NOTEBOOK SI_ENERGY_COMPANY
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/The_Energy_Company' 
        QUERY_WAREHOUSE = 'AI_WH'
        MAIN_FILE = 'SI_ENERGY_COMPANY.ipynb';
ALTER NOTEBOOK SI_ENERGY_COMPANY ADD LIVE VERSION FROM LAST;

-- Whether to execute the notebook or not during initial demo setup
{% if EXECUTE_NOTEBOOKS %}
    EXECUTE NOTEBOOK SI_ENERGY_COMPANY();
{%- endif -%}