USE ROLE AI_ENGINEER;
CREATE SCHEMA IF NOT EXISTS AI_DEVELOPMENT.SI_CLINICAL_TRIAL;
USE SCHEMA AI_DEVELOPMENT.SI_CLINICAL_TRIAL;

-- Create Notebooks
CREATE NOTEBOOK SI_CLINICAL_TRIAL
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SNOWFLAKE_INTELLIGENCE_DEMOS/branches/main/use_cases/Clinical_Trial' 
        QUERY_WAREHOUSE = 'AI_WH'
        MAIN_FILE = 'SI_CLINICAL_TRIAL.ipynb';
ALTER NOTEBOOK SI_CLINICAL_TRIAL ADD LIVE VERSION FROM LAST;

-- Whether to execute the notebook or not during initial demo setup
{% if EXECUTE_NOTEBOOKS %}
    EXECUTE NOTEBOOK SI_CLINICAL_TRIAL();
{%- endif -%}