
-- Example (manual run):
-- 
-- CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_HISTORICAL_ENDPOINTS_RAW(ARRAY_CONSTRUCT('de','nl','fr','uk'), TRUE, DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE()))::STRING, LAST_DAY(CURRENT_DATE())::STRING);
use role ai_engineer;
use warehouse ai_wh;




CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_HISTORICAL_ENDPOINTS_RAW(ARRAY_CONSTRUCT('de','nl','fr','uk'), TRUE, DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE()))::STRING, DATEADD('days', -1, CURRENT_DATE())::STRING);

--CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_HISTORICAL_ENDPOINTS_RAW(ARRAY_CONSTRUCT('de','nl','fr','uk'), TRUE,, NULL);

CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_FORECAST_ENDPOINTS(ARRAY_CONSTRUCT('de','nl','fr','uk'), TRUE);


CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.GENERATE_LLM_TIME_SERIES_METADATA();

CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TRANSFORM_MARKET_DATA_FROM_VIEWS(TRUE); 



ALTER CORTEX SEARCH SERVICE AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.ENERGY_TIME_SERIES_SEARCH REFRESH;
ALTER CORTEX SEARCH SERVICE AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TIME_SERIES_SEARCH REFRESH;


-- Parent: nightly ingestion of raw endpoints for DE, NL, FR, UK
CREATE OR ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_INGEST_HISTORICAL_ENDPOINTS_RAW
  WAREHOUSE = AI_WH
  SCHEDULE = 'USING CRON 0 3 * * * Europe/Berlin'
AS
  CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_HISTORICAL_ENDPOINTS_RAW(
    ARRAY_CONSTRUCT('de','nl','fr','uk'), TRUE, TRUE, NULL, NULL
  );


-- Child: run transformation right after ingestion completes
CREATE OR ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_TRANSFORM_MARKET_DATA_FROM_VIEWS_HISTORICAL
  WAREHOUSE = COMPUTE_WH
  AFTER AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_INGEST_HISTORICAL_ENDPOINTS_RAW
AS
BEGIN
  CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TRANSFORM_MARKET_DATA_FROM_VIEWS(FALSE);

END;

-- Enable the task chain (does not run immediately; just schedules future runs)


CREATE OR ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_INGEST_FORECAST_ENDPOINTS
  WAREHOUSE = AI_WH
  SCHEDULE = 'USING CRON 0 3 * * * Europe/Berlin'
AS
  CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_FORECAST_ENDPOINTS(
    ARRAY_CONSTRUCT('de','nl','fr','uk'), TRUE
  );
-- Child: run transformation right after ingestion completes
CREATE OR ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_TRANSFORM_MARKET_DATA_FROM_VIEWS_FORECAST
  WAREHOUSE = COMPUTE_WH
  AFTER AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_INGEST_FORECAST_ENDPOINTS
AS
BEGIN
  CALL AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TRANSFORM_MARKET_DATA_FROM_VIEWS(FALSE);
END;


--grant USAGE on procedure AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TRANSFORM_MARKET_DATA_FROM_VIEWS() to role AI_ENGINEER;
--grant USAGE on procedure AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_HISTORICAL_ENDPOINTS_RAW(ARRAY, BOOLEAN, BOOLEAN, STRING, STRING) to role AI_ENGINEER;
--grant USAGE on procedure AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.INGEST_FORECAST_ENDPOINTS(ARRAY, BOOLEAN) to role AI_ENGINEER;

ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_TRANSFORM_MARKET_DATA_FROM_VIEWS_HISTORICAL RESUME;

ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_INGEST_HISTORICAL_ENDPOINTS_RAW RESUME;
ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_TRANSFORM_MARKET_DATA_FROM_VIEWS_FORECAST RESUME;
ALTER TASK AI_DEVELOPMENT.SI_ENERGY_TRADING_COMPANY.TASK_INGEST_FORECAST_ENDPOINTS RESUME;




